import os
import logging
import json
from pathlib import Path
from datetime import datetime
from src.config import BASE_DIR, DB_PATH

logger = logging.getLogger("DB_Adapter")

class DatabaseAdapter:
    """
    Abstracts database connection and dialect-specific queries 
    supporting both DuckDB (local/OLAP) and PostgreSQL (production).
    """
    def __init__(self, workspace_id: str = "default"):
        # Read from environment
        self.workspace_id = workspace_id
        self.database_url = os.environ.get("DATABASE_URL")
        self.dialect = "duckdb"
        
        from src.config import get_workspace_db_path, get_workspace_file_paths
        self.db_path = get_workspace_db_path(workspace_id)
        self.gold_query = None
        
        if self.database_url and (self.database_url.startswith("postgresql://") or self.database_url.startswith("postgres://")):
            # Normalize database URL scheme for psycopg2 (replace postgres:// with postgresql://)
            if self.database_url.startswith("postgres://"):
                self.database_url = self.database_url.replace("postgres://", "postgresql://", 1)
            
            # Verify if PostgreSQL is reachable
            try:
                import psycopg2
                # Attempt to establish connection with a short timeout
                conn = psycopg2.connect(self.database_url, connect_timeout=3)
                conn.close()
                self.dialect = "postgres"
                logger.info(f"Database Adapter: Successfully connected to PostgreSQL (workspace: {workspace_id}).")
            except Exception as e:
                logger.warning(
                    f"\n{'!'*60}\n"
                    f" [WARNING] PostgreSQL connection failed: {e}\n"
                    f" Falling back to local DuckDB database (workspace: {workspace_id}).\n"
                    f"{'!'*60}\n"
                )
                self.dialect = "duckdb"
        else:
            self.dialect = "duckdb"
            logger.info(f"Database Adapter: Operating with DuckDB (workspace: {workspace_id}). Path: {self.db_path}")

        # Load cached schema profile if it exists in the workspace
        self.profile = None
        paths = get_workspace_file_paths(workspace_id)
        profile_path = paths["profile_json"]
        if profile_path.exists():
            try:
                with open(profile_path, "r") as f:
                    self.profile = json.load(f)
                logger.info(f"Database Adapter: Dynamic profile loaded automatically from {profile_path}")
            except Exception as e:
                logger.warning(f"Database Adapter: Failed to load cached profile: {e}")

    def load_profile(self, profile: dict):
        """Explicitly loads a schema profile dictionary."""
        self.profile = profile

    def set_gold_query(self, query: str):
        """Sets the dynamic Gold query generated by the LLM."""
        self.gold_query = query

    def get_connection(self):
        """Returns a native database connection based on the dialect, with schema scoping applied."""
        if self.dialect == "postgres":
            import psycopg2
            conn = psycopg2.connect(self.database_url)
            # Create schema if not exists and scope connection to it
            cursor = conn.cursor()
            cursor.execute(f"CREATE SCHEMA IF NOT EXISTS workspace_{self.workspace_id}")
            cursor.execute(f"SET search_path TO workspace_{self.workspace_id}")
            cursor.close()
            return conn
        else:
            import duckdb
            # Ensure the parent data directory exists
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            return duckdb.connect(str(self.db_path))

    def ingest_csv(self, file_path: Path, table_name: str):
        """Performs dynamic high-performance native or chunked streaming CSV ingestion to avoid out-of-memory errors."""
        filename = file_path.name
        conn = self.get_connection()
        
        if self.dialect == "duckdb":
            # Use DuckDB's native disk-streaming read_csv_auto command (extremely fast, zero python memory overhead)
            cursor = conn.cursor()
            columns_to_load = list(self.profile.keys()) if self.profile else []
            if not columns_to_load:
                # Fallback: read columns from CSV header
                import pandas as pd
                df_cols = pd.read_csv(file_path, nrows=0).columns
                columns_to_load = list(df_cols)
                
            columns_str = ", ".join([f'"{c}"' for c in columns_to_load])
            types_str = ", ".join([f"'{c}': 'VARCHAR'" for c in columns_to_load])
            
            # Format Windows paths safely for DuckDB SQL
            path_str = str(file_path.absolute()).replace("\\", "/")
            
            query = f"""
            INSERT INTO {table_name} ({columns_str}, ingested_at, source_file)
            SELECT {columns_str}, CURRENT_TIMESTAMP as ingested_at, '{filename}' as source_file
            FROM read_csv_auto('{path_str}', types={{{types_str}}})
            """
            cursor.execute(query)
            conn.commit()
            conn.close()
            logger.info(f"Database Adapter: Native DuckDB CSV ingestion complete for {filename}.")
        else:
            # PostgreSQL or SQLite fallback: stream using pandas chunksize to prevent RAM spikes
            import pandas as pd
            chunksize = 50000
            cursor = conn.cursor()
            
            placeholder = "%s" if self.dialect == "postgres" else "?"
            
            first_chunk = True
            for chunk in pd.read_csv(file_path, chunksize=chunksize):
                chunk["ingested_at"] = datetime.now().isoformat()
                chunk["source_file"] = filename
                df_str = chunk.astype(str)
                
                columns = list(df_str.columns)
                if first_chunk:
                    columns_str = ", ".join([f'"{col}"' for col in columns])
                    placeholders_str = ", ".join([placeholder] * len(columns))
                    insert_query = f"INSERT INTO {table_name} ({columns_str}) VALUES ({placeholders_str})"
                    first_chunk = False
                    
                records = [tuple(row) for row in df_str.values]
                cursor.executemany(insert_query, records)
                conn.commit()
                
            conn.close()
            logger.info(f"Database Adapter: Chunked streaming CSV Ingestion complete for {filename}.")

    def get_schema_queries(self) -> list[str]:
        """Returns dialect-specific DDL queries for initializing tables dynamically or statically."""
        if not self.profile:
            return self._get_static_schema_queries()
            
        queries = []
        
        # 1. Bronze Table DDL (all raw fields as TEXT)
        bronze_cols = []
        for col_name in self.profile.keys():
            bronze_cols.append(f'"{col_name}" TEXT')
        bronze_cols_str = ",\n            ".join(bronze_cols)
        
        # 2. Silver Table DDL (cast based on semantic roles)
        silver_cols = []
        for col_name, details in self.profile.items():
            role = details["role"]
            if role == "date":
                col_type = "DATE"
            elif role in ("measure", "currency"):
                col_type = "REAL"
            else:
                col_type = "TEXT"
            silver_cols.append(f'"{col_name}" {col_type}')
        silver_cols.append("cleaned_at TIMESTAMP")
        silver_cols_str = ",\n            ".join(silver_cols)
        
        # 3. Quarantine Table DDL (every field prefixed with raw_)
        quarantine_cols = []
        for col_name in self.profile.keys():
            quarantine_cols.append(f'"raw_{col_name}" TEXT')
        quarantine_cols.extend([
            "source_file TEXT",
            "ingested_at TEXT",
            "rejection_reason TEXT",
            "quarantined_at TIMESTAMP"
        ])
        quarantine_cols_str = ",\n            ".join(quarantine_cols)
        
        # Dialect DDL customization with sequences for Postgres/DuckDB
        if self.dialect in ("postgres", "duckdb"):
            queries.extend([
                "CREATE SEQUENCE IF NOT EXISTS silver_seq",
                "CREATE SEQUENCE IF NOT EXISTS quarantine_seq",
                "DROP TABLE IF EXISTS bronze_raw_sales CASCADE",
                f"CREATE TABLE bronze_raw_sales (\n            {bronze_cols_str},\n            ingested_at TIMESTAMP,\n            source_file TEXT\n        )",
                "DROP TABLE IF EXISTS silver_clean_sales CASCADE",
                f"CREATE TABLE silver_clean_sales (\n            id INTEGER DEFAULT nextval('silver_seq') PRIMARY KEY,\n            {silver_cols_str}\n        )",
                "DROP TABLE IF EXISTS quarantine_rejected_sales CASCADE",
                f"CREATE TABLE quarantine_rejected_sales (\n            id INTEGER DEFAULT nextval('quarantine_seq') PRIMARY KEY,\n            {quarantine_cols_str}\n        )"
            ])
        else:
            # SQLite fallback
            queries.extend([
                "DROP TABLE IF EXISTS bronze_raw_sales",
                f"CREATE TABLE bronze_raw_sales (\n            {bronze_cols_str},\n            ingested_at TIMESTAMP,\n            source_file TEXT\n        )",
                "DROP TABLE IF EXISTS silver_clean_sales",
                f"CREATE TABLE silver_clean_sales (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            {silver_cols_str}\n        )",
                "DROP TABLE IF EXISTS quarantine_rejected_sales",
                f"CREATE TABLE quarantine_rejected_sales (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            {quarantine_cols_str}\n        )"
            ])
            
        return queries

    def get_quarantine_transform_query(self) -> str:
        """Returns dialect-specific query to extract rejections into the quarantine table."""
        if not self.profile:
            return self._get_static_quarantine_query()
            
        timestamp_func = "CURRENT_TIMESTAMP" if self.dialect in ("postgres", "duckdb") else "datetime('now')"
        
        csv_cols = list(self.profile.keys())
        raw_cols_str = ", ".join([f'"raw_{col}"' for col in csv_cols])
        select_cols_str = ", ".join([f'"{col}"' for col in csv_cols])
        
        union_queries = []
        
        # 1. Null Violations in Date, ID, or Dimension roles
        for col_name, details in self.profile.items():
            if details["role"] in ("date", "id", "dimension"):
                union_queries.append(f"""
                SELECT {select_cols_str}, source_file, ingested_at,
                       'Null value in required column: {col_name}', {timestamp_func}
                FROM bronze_raw_sales
                WHERE "{col_name}" IS NULL OR "{col_name}" = 'None' OR "{col_name}" = ''
                """)
                
        # 2. Negative Metric Violations
        for col_name, details in self.profile.items():
            if details["role"] == "measure":
                union_queries.append(f"""
                SELECT {select_cols_str}, source_file, ingested_at,
                       'Negative Numeric Metric: {col_name}', {timestamp_func}
                FROM bronze_raw_sales
                WHERE "{col_name}" IS NOT NULL AND "{col_name}" != 'None' AND "{col_name}" != ''
                  AND CAST("{col_name}" AS REAL) < 0
                """)
                
        # 3. Duplicate Violations
        id_cols = [col for col, details in self.profile.items() if details["role"] == "id"]
        date_cols = [col for col, details in self.profile.items() if details["role"] == "date"]
        
        partition_keys = []
        if id_cols:
            partition_keys = id_cols
        else:
            dim_cols = [col for col, details in self.profile.items() if details["role"] == "dimension"]
            partition_keys = dim_cols + date_cols
            
        if not partition_keys:
            partition_keys = csv_cols
            
        partition_cols_str = ", ".join([f'"{k}"' for k in partition_keys])
        
        exclusion_conds = []
        for col_name, details in self.profile.items():
            if details["role"] in ("date", "id", "dimension"):
                exclusion_conds.append(f'("{col_name}" IS NOT NULL AND "{col_name}" != \'None\' AND "{col_name}" != \'\')')
            if details["role"] == "measure":
                exclusion_conds.append(f'("{col_name}" IS NOT NULL AND "{col_name}" != \'None\' AND "{col_name}" != \'\' AND CAST("{col_name}" AS REAL) >= 0)')
                
        exclusion_str = " AND ".join(exclusion_conds) if exclusion_conds else "1=1"
        
        union_queries.append(f"""
        SELECT {select_cols_str}, source_file, ingested_at,
               'Duplicate Transaction', {timestamp_func}
        FROM (
            SELECT *,
                   ROW_NUMBER() OVER(
                       PARTITION BY {partition_cols_str}
                       ORDER BY ingested_at DESC
                   ) as rn
            FROM bronze_raw_sales
            WHERE {exclusion_str}
        ) AS dups
        WHERE rn > 1
        """)
        
        union_sql = "\n            UNION ALL\n            ".join(union_queries)
        
        return f"""
        INSERT INTO quarantine_rejected_sales (
            {raw_cols_str}, source_file, ingested_at, rejection_reason, quarantined_at
        )
        {union_sql};
        """

    def get_silver_transform_query(self) -> str:
        """Returns dynamic or static query to populate silver_clean_sales."""
        if not self.profile:
            return self._get_static_silver_query()
            
        timestamp_func = "CURRENT_TIMESTAMP" if self.dialect in ("postgres", "duckdb") else "datetime('now')"
        
        csv_cols = list(self.profile.keys())
        id_cols = [col for col, details in self.profile.items() if details["role"] == "id"]
        date_cols = [col for col, details in self.profile.items() if details["role"] == "date"]
        
        partition_keys = []
        if id_cols:
            partition_keys = id_cols
        else:
            dim_cols = [col for col, details in self.profile.items() if details["role"] == "dimension"]
            partition_keys = dim_cols + date_cols
            
        if not partition_keys:
            partition_keys = csv_cols
            
        partition_cols_str = ", ".join([f'"{k}"' for k in partition_keys])
        
        valid_conds = []
        for col_name, details in self.profile.items():
            if details["role"] in ("date", "id", "dimension"):
                valid_conds.append(f'("{col_name}" IS NOT NULL AND "{col_name}" != \'None\' AND "{col_name}" != \'\')')
            if details["role"] == "measure":
                valid_conds.append(f'("{col_name}" IS NOT NULL AND "{col_name}" != \'None\' AND "{col_name}" != \'\' AND CAST("{col_name}" AS REAL) >= 0)')
                
        valid_conds_str = " AND ".join(valid_conds) if valid_conds else "1=1"
        
        silver_insert_cols = ", ".join([f'"{col}"' for col in csv_cols])
        
        silver_selects = []
        for col_name, details in self.profile.items():
            role = details["role"]
            if role == "date":
                date_cast = f'CAST("{col_name}" AS DATE)' if self.dialect in ("postgres", "duckdb") else f'date("{col_name}")'
                silver_selects.append(date_cast)
            elif role in ("measure", "currency"):
                silver_selects.append(f'CAST("{col_name}" AS REAL)')
            else:
                silver_selects.append(f'"{col_name}"')
                
        silver_selects_str = ", ".join(silver_selects)
        
        return f"""
        WITH ranked_bronze AS (
            SELECT 
                *,
                ROW_NUMBER() OVER(
                    PARTITION BY {partition_cols_str}
                    ORDER BY ingested_at DESC
                ) as rn
            FROM bronze_raw_sales
            WHERE {valid_conds_str}
        )
        INSERT INTO silver_clean_sales ({silver_insert_cols}, cleaned_at)
        SELECT 
            {silver_selects_str},
            {timestamp_func} as cleaned_at
        FROM ranked_bronze
        WHERE rn = 1;
        """

    def get_gold_aggregation_query(self) -> str:
        """Returns dynamic gold query or static query to populate the gold aggregates."""
        if self.gold_query:
            return self.gold_query
        return self._get_static_gold_query()

    def _get_static_schema_queries(self) -> list[str]:
        """Static query mappings for original e-commerce baseline schema."""
        if self.dialect in ("postgres", "duckdb"):
            return [
                "CREATE SEQUENCE IF NOT EXISTS silver_seq",
                "CREATE SEQUENCE IF NOT EXISTS quarantine_seq",
                "DROP TABLE IF EXISTS bronze_raw_sales CASCADE",
                """
                CREATE TABLE bronze_raw_sales (
                    date TEXT,
                    category TEXT,
                    revenue TEXT,
                    cost TEXT,
                    units_sold TEXT,
                    ingested_at TIMESTAMP,
                    source_file TEXT
                );
                """,
                "DROP TABLE IF EXISTS silver_clean_sales CASCADE",
                """
                CREATE TABLE silver_clean_sales (
                    id INTEGER DEFAULT nextval('silver_seq') PRIMARY KEY,
                    date DATE,
                    category TEXT,
                    revenue REAL,
                    cost REAL,
                    units_sold INTEGER,
                    profit REAL,
                    cleaned_at TIMESTAMP
                );
                """,
                "DROP TABLE IF EXISTS quarantine_rejected_sales CASCADE",
                """
                CREATE TABLE quarantine_rejected_sales (
                    id INTEGER DEFAULT nextval('quarantine_seq') PRIMARY KEY,
                    raw_date TEXT,
                    raw_category TEXT,
                    raw_revenue TEXT,
                    raw_cost TEXT,
                    raw_units_sold TEXT,
                    source_file TEXT,
                    ingested_at TEXT,
                    rejection_reason TEXT,
                    quarantined_at TIMESTAMP
                );
                """
            ]
        else:
            return [
                "DROP TABLE IF EXISTS bronze_raw_sales",
                """
                CREATE TABLE bronze_raw_sales (
                    date TEXT,
                    category TEXT,
                    revenue TEXT,
                    cost TEXT,
                    units_sold TEXT,
                    ingested_at TIMESTAMP,
                    source_file TEXT
                );
                """,
                "DROP TABLE IF EXISTS silver_clean_sales",
                """
                CREATE TABLE silver_clean_sales (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    date DATE,
                    category TEXT,
                    revenue REAL,
                    cost REAL,
                    units_sold INTEGER,
                    profit REAL,
                    cleaned_at TIMESTAMP
                );
                """,
                "DROP TABLE IF EXISTS quarantine_rejected_sales",
                """
                CREATE TABLE quarantine_rejected_sales (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    raw_date TEXT,
                    raw_category TEXT,
                    raw_revenue TEXT,
                    raw_cost TEXT,
                    raw_units_sold TEXT,
                    source_file TEXT,
                    ingested_at TEXT,
                    rejection_reason TEXT,
                    quarantined_at TIMESTAMP
                );
                """
            ]

    def _get_static_quarantine_query(self) -> str:
        """Static query to extract rejections into the quarantine table."""
        timestamp_func = "CURRENT_TIMESTAMP" if self.dialect in ("postgres", "duckdb") else "datetime('now')"
        return f"""
            INSERT INTO quarantine_rejected_sales (
                raw_date, raw_category, raw_revenue, raw_cost, raw_units_sold, 
                source_file, ingested_at, rejection_reason, quarantined_at
            )
            SELECT date, category, revenue, cost, units_sold, source_file, ingested_at, 
                   'Missing/Invalid Date', {timestamp_func}
            FROM bronze_raw_sales
            WHERE date IS NULL OR date = 'None' OR date = ''
            UNION ALL
            SELECT date, category, revenue, cost, units_sold, source_file, ingested_at, 
                   'Missing/Invalid Category', {timestamp_func}
            FROM bronze_raw_sales
            WHERE (date IS NOT NULL AND date != 'None' AND date != '')
              AND (category IS NULL OR category = 'None' OR category = '')
            UNION ALL
            SELECT date, category, revenue, cost, units_sold, source_file, ingested_at, 
                   'Negative Numeric Metric(s)', {timestamp_func}
            FROM bronze_raw_sales
            WHERE (date IS NOT NULL AND date != 'None' AND date != '')
              AND (category IS NOT NULL AND category != 'None' AND category != '')
              AND (CAST(revenue AS REAL) < 0 OR CAST(cost AS REAL) < 0 OR CAST(units_sold AS INTEGER) < 0)
            UNION ALL
            SELECT date, category, revenue, cost, units_sold, source_file, ingested_at, 
                   'Duplicate Transaction', {timestamp_func}
            FROM (
                SELECT *,
                       ROW_NUMBER() OVER(
                           PARTITION BY date, category, units_sold, revenue 
                           ORDER BY ingested_at DESC
                       ) as rn
                FROM bronze_raw_sales
                WHERE date IS NOT NULL AND date != 'None' AND date != ''
                  AND category IS NOT NULL AND category != 'None' AND category != ''
            ) AS dups
            WHERE rn > 1 
              AND CAST(revenue AS REAL) >= 0 
              AND CAST(cost AS REAL) >= 0 
              AND CAST(units_sold AS INTEGER) >= 0;
        """

    def _get_static_silver_query(self) -> str:
        """Static query to populate the silver_clean_sales layer."""
        timestamp_func = "CURRENT_TIMESTAMP" if self.dialect in ("postgres", "duckdb") else "datetime('now')"
        date_cast = "CAST(date AS DATE)" if self.dialect in ("postgres", "duckdb") else "date(date)"
        return f"""
            WITH ranked_bronze AS (
                SELECT 
                    date,
                    category,
                    CAST(revenue AS REAL) as clean_revenue,
                    CAST(cost AS REAL) as clean_cost,
                    CAST(units_sold AS INTEGER) as clean_units,
                    ingested_at,
                    source_file,
                    ROW_NUMBER() OVER(
                        PARTITION BY date, category, units_sold, revenue 
                        ORDER BY ingested_at DESC
                    ) as rn
                FROM bronze_raw_sales
                WHERE date IS NOT NULL 
                  AND date != 'None' 
                  AND date != ''
                  AND category IS NOT NULL 
                  AND category != 'None' 
                  AND category != ''
            )
            INSERT INTO silver_clean_sales (date, category, revenue, cost, units_sold, profit, cleaned_at)
            SELECT 
                {date_cast} as date,
                category,
                clean_revenue,
                clean_cost,
                clean_units,
                (clean_revenue - clean_cost) as profit,
                {timestamp_func} as cleaned_at
            FROM ranked_bronze
            WHERE rn = 1 
              AND clean_revenue >= 0 
              AND clean_cost >= 0 
              AND clean_units >= 0;
        """

    def _get_static_gold_query(self) -> str:
        """Static query to populate the gold_monthly_metrics aggregates."""
        if self.dialect in ("postgres", "duckdb"):
            return """
                WITH monthly_sales AS (
                    SELECT 
                        TO_CHAR(date, 'YYYY-MM') as month,
                        category,
                        SUM(revenue) as category_revenue,
                        SUM(units_sold) as category_units
                    FROM silver_clean_sales
                    GROUP BY month, category
                ),
                ranked_categories AS (
                    SELECT 
                        month,
                        category,
                        ROW_NUMBER() OVER (PARTITION BY month ORDER BY category_revenue DESC) as rk
                    FROM monthly_sales
                ),
                monthly_aggregates AS (
                    SELECT 
                        TO_CHAR(date, 'YYYY-MM') as month,
                        ROUND(SUM(revenue)::numeric, 2) as revenue,
                        ROUND(SUM(cost)::numeric, 2) as cost,
                        ROUND(CAST((SUM(revenue) - SUM(cost)) / SUM(revenue) AS numeric), 4) as profit_margin,
                        SUM(units_sold) as units_sold
                    FROM silver_clean_sales
                    GROUP BY month
                )
                INSERT INTO gold_monthly_metrics (month, revenue, cost, profit_margin, units_sold, top_category)
                SELECT 
                    ma.month,
                    ma.revenue,
                    ma.cost,
                    ma.profit_margin,
                    ma.units_sold,
                    rc.category as top_category
                FROM monthly_aggregates ma
                JOIN ranked_categories rc ON ma.month = rc.month AND rc.rk = 1
                ORDER BY ma.month ASC;
            """
        else:
            return """
                WITH monthly_sales AS (
                    SELECT 
                        strftime('%Y-%m', date) as month,
                        category,
                        SUM(revenue) as category_revenue,
                        SUM(units_sold) as category_units
                    FROM silver_clean_sales
                    GROUP BY month, category
                ),
                ranked_categories AS (
                    SELECT 
                        month,
                        category,
                        ROW_NUMBER() OVER (PARTITION BY month ORDER BY category_revenue DESC) as rk
                    FROM monthly_sales
                ),
                monthly_aggregates AS (
                    SELECT 
                        strftime('%Y-%m', date) as month,
                        ROUND(SUM(revenue), 2) as revenue,
                        ROUND(SUM(cost), 2) as cost,
                        ROUND((SUM(revenue) - SUM(cost)) / SUM(revenue), 4) as profit_margin,
                        SUM(units_sold) as units_sold
                    FROM silver_clean_sales
                    GROUP BY month
                )
                INSERT INTO gold_monthly_metrics (month, revenue, cost, profit_margin, units_sold, top_category)
                SELECT 
                    ma.month,
                    ma.revenue,
                    ma.cost,
                    ma.profit_margin,
                    ma.units_sold,
                    rc.category as top_category
                FROM monthly_aggregates ma
                JOIN ranked_categories rc ON ma.month = rc.month AND rc.rk = 1
                ORDER BY ma.month ASC;
            """
